apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-produtos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-produtos
  template:
    metadata:
      labels:
        app: api-produtos
    spec:
      containers:
      - name: api-produtos
        image: esveraldo/api-produtos:v1
        ports:
        - containerPort: 3000
        env:
        - name: DB_USER
          value: "adminsql"
        - name: DB_PASSWORD
          value: "SenhaForte123!"
        - name: DB_SERVER
          value: "sql-aula-produtos-esveraldo.database.windows.net"
        - name: DB_NAME
          value: "produtosdb"
